recipe: default.v1
language: pt

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "word"
  min_ngram: 1
  max_ngram: 1
- name: DIETClassifier
  epochs: 50
- name: FallbackClassifier
  threshold: 0.1

policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 2
  epochs: 50
- name: RulePolicy
  core_fallback_threshold: 0.0  # Desativa fallback automático
  enable_fallback_prediction: false
assistant_id: 20250728-124659-relaxed-apartment
